### ISSUE TITLE
dust 1.1.1 thread 'main' panicked - global thread pool has not been initialized

### ISSUE THREAD

**Issue by peterjc** [conda-forge/dust-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Trying dust on a recently rebuilt Linux cluster, now on Debian:

```console
$ uname -srvmpio
Linux 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 unknown unknown GNU/Linux

$ conda list dust
# packages in environment at /mnt/apps/users/pcock/conda:
#
# Name                    Version                   Build  Channel
dust                      1.1.1                h9678756_0    conda-forge
```

```console
$ dust
thread 'main' panicked at /home/conda/feedstock_root/build_artifacts/dust_1721273795216/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:168:10:
The global thread pool has not been initialized.: ThreadPoolBuildError { kind: GlobalPoolAlreadyInitialized }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```console
$ RUST_BACKTRACE=1 dust
thread 'main' panicked at /home/conda/feedstock_root/build_artifacts/dust_1721273795216/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:168:10:
The global thread pool has not been initialized.: ThreadPoolBuildError { kind: GlobalPoolAlreadyInitialized }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```console
$ RUST_BACKTRACE=full dust
thread 'main' panicked at /home/conda/feedstock_root/build_artifacts/dust_1721273795216/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:168:10:
The global thread pool has not been initialized.: ThreadPoolBuildError { kind: GlobalPoolAlreadyInitialized }
stack backtrace:
   0:     0x55739a99cdd2 - <unknown>
   1:     0x55739a8cc82b - <unknown>
   2:     0x55739a974442 - <unknown>
   3:     0x55739a9a20a9 - <unknown>
   4:     0x55739a9a18ce - <unknown>
   5:     0x55739a9a2af4 - <unknown>
   6:     0x55739a9a2412 - <unknown>
   7:     0x55739a9a2369 - <unknown>
   8:     0x55739a9a2356 - <unknown>
   9:     0x55739a8031f2 - <unknown>
  10:     0x55739a803605 - <unknown>
  11:     0x55739a8e6a6a - <unknown>
  12:     0x55739a83bf3c - <unknown>
  13:     0x55739a811643 - <unknown>
  14:     0x55739a84d719 - <unknown>
  15:     0x55739a817603 - <unknown>
  16:     0x55739a8573f1 - <unknown>
  17:     0x7f2d58a5e24a - <unknown>
  18:     0x7f2d58a5e305 - __libc_start_main
  19:     0x55739a81002c - <unknown>
  20:                0x0 - <unknown>
```

### Installed packages

```shell
# packages in environment at /mnt/apps/users/pcock/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_1    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.3               hb9d3cd8_1    conda-forge
ca-certificates           2024.12.14           hbcca054_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h06ac9bb_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
conda                     24.11.0         py312h7900ff3_0    conda-forge
conda-libmamba-solver     24.9.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.4.0              pyha770c72_1    conda-forge
conda-package-streaming   0.11.0             pyhd8ed1ab_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
dust                      1.1.1                h9678756_0    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
frozendict                2.4.6           py312h66e93f0_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_1    conda-forge
hpack                     4.0.0              pyhd8ed1ab_1    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_1    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_1    conda-forge
jsonpointer               3.0.0           py312h7900ff3_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libarchive                3.7.7                h4585015_2    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblzma                   5.6.3                hb9d3cd8_1    conda-forge
libmamba                  1.5.11               hf72d635_0    conda-forge
libmambapy                1.5.11          py312hf3f0a4e_0    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsolv                   0.7.30               h3509ff9_0    conda-forge
libsqlite                 3.47.2               hee588c1_0    conda-forge
libssh2                   1.11.1               hf672d98_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.5               h0d44e9d_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lz4-c                     1.10.0               h5888daf_1    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mamba                     1.5.11          py312h9460a1c_0    conda-forge
menuinst                  2.2.0           py312h7900ff3_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
packaging                 24.2               pyhd8ed1ab_2    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_1    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py312h66e93f0_2    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
python                    3.12.8          h9e4cc4f_1_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.5.post0         hb9d3cd8_0    conda-forge
reproc-cpp                14.2.5.post0         h5888daf_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_1    conda-forge
ruamel.yaml               0.18.6          py312h66e93f0_1    conda-forge
ruamel.yaml.clib          0.2.8           py312h66e93f0_1    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_0    conda-forge
truststore                0.10.0             pyhd8ed1ab_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
active environment : None
            shell level : 0
       user config file : /home/pcock/.condarc
 populated config files : /mnt/apps/users/pcock/conda/.condarc
                          /home/pcock/.condarc
          conda version : 24.11.0
    conda-build version : not installed
         python version : 3.12.8.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen3
                          __conda=24.11.0=0
                          __glibc=2.36=0
                          __linux=6.1.0=0
                          __unix=0=0
       base environment : /mnt/apps/users/pcock/conda  (writable)
      conda av data dir : /mnt/apps/users/pcock/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /mnt/apps/users/pcock/conda/pkgs
                          /home/pcock/.conda/pkgs
       envs directories : /mnt/apps/users/pcock/conda/envs
                          /home/pcock/.conda/envs
               platform : linux-64
             user-agent : conda/24.11.0 requests/2.32.3 CPython/3.12.8 Linux/6.1.0-28-amd64 debian/12.8 glibc/2.36 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.11
                UID:GID : 896600025:896600025
             netrc file : None
           offline mode : False
```

**Comment by peterjc** [comment]
Confirmed to work normally from a worker node, just fails with the above cryptic error on the cluster head node.

i.e. This does not seem to be a conda-forge issue after all, but a less-than-helpful error message from dust itself in a corner case of some kind.

Closing.

**Comment by peterjc** [comment]
Just ran into this again - on the same server. I update the conda-forge dust from 1.1.1 to 1.1.2 but the problem remains.

The upstream issue is https://github.com/bootandy/dust/issues/296 and should be fixed with https://github.com/bootandy/dust/pull/310 included in the recent dust v1.1.2, and yes, https://github.com/bootandy/dust/releases/download/v1.1.2/dust-v1.1.2-aarch64-unknown-linux-musl.tar.gz works.

However, the conda-forge provided v1.1.2 (`dust-1.1.2-h8fae777_0`) still has the panicked error:

```
$ dust .
thread 'main' panicked at /home/conda/feedstock_root/build_artifacts/dust_1740751738383/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:168:10:
The global thread pool has not been initialized.: ThreadPoolBuildError { kind: GlobalPoolAlreadyInitialized }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It looks like rayon-core 1.12.1 is the latest release, so I'm unsure what might be amiss.

**Comment by Zeitsperre** [comment]
@peterjc Hi there, I'm wondering if this is still an issue for you. I'm going to merge the latest update (v1.2.3) which should be available a few hours afterwards. The conda package is a very simple compilation of `dust`, so it might be that either the installation flags need to be adjusted or we could be missing a library for multithreaded support.

I'll try raising this higher if this is still the case.
